language: node_js

services:
  - docker

before_install:
  - docker build -t nob786/eatsabytee ./microservices/auth-service
  - docker run -d -p 4000:4000 nob786/eatsabytee

script:
  - bundle exec rake test
